[package]
name = "changelogs"
version = "0.0.0"
authors = ["aedm <korteur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
octocrab = "0.8"
tokio = { version = "1.0.0", features = ["full", "tracing"] }